<#
    Generate the Partnera application icon (no external assets, no network).

    Produces:
      assets\partnera.ico             - Windows shortcut icon (256px PNG-in-ICO)
      packages\web\src\brand-icon.ts  - base64 512px PNG for the web PWA/favicon

    Pure System.Drawing; safe to re-run. ASCII-only source (do not add non-ASCII
    characters - Windows PowerShell 5.1 may misparse a UTF-8 file without a BOM).
#>
$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

$Root = Split-Path -Parent $PSScriptRoot
$AssetsDir = Join-Path $Root "assets"
if (-not (Test-Path $AssetsDir)) { New-Item -ItemType Directory -Path $AssetsDir | Out-Null }

function New-IconBitmap([int]$size) {
    $bmp = New-Object System.Drawing.Bitmap($size, $size, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
    $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAliasGridFit
    $g.Clear([System.Drawing.Color]::Transparent)

    $d = [int]($size * 0.36)
    $path = New-Object System.Drawing.Drawing2D.GraphicsPath
    $path.AddArc(0, 0, $d, $d, 180, 90)
    $path.AddArc($size - $d, 0, $d, $d, 270, 90)
    $path.AddArc($size - $d, $size - $d, $d, $d, 0, 90)
    $path.AddArc(0, $size - $d, $d, $d, 90, 90)
    $path.CloseFigure()
    $brush = New-Object System.Drawing.SolidBrush ([System.Drawing.ColorTranslator]::FromHtml("#4F46E5"))
    $g.FillPath($brush, $path)

    $font = New-Object System.Drawing.Font("Segoe UI", [single]($size * 0.56), [System.Drawing.FontStyle]::Bold, [System.Drawing.GraphicsUnit]::Pixel)
    $sf = New-Object System.Drawing.StringFormat
    $sf.Alignment = [System.Drawing.StringAlignment]::Center
    $sf.LineAlignment = [System.Drawing.StringAlignment]::Center
    $white = New-Object System.Drawing.SolidBrush ([System.Drawing.Color]::White)
    $g.DrawString("P", $font, $white, (New-Object System.Drawing.RectangleF(0, 0, $size, $size)), $sf)

    $g.Dispose()
    return $bmp
}

function Get-PngBytes($bmp) {
    $ms = New-Object System.IO.MemoryStream
    $bmp.Save($ms, [System.Drawing.Imaging.ImageFormat]::Png)
    $bytes = $ms.ToArray()
    $ms.Dispose()
    return , $bytes   # comma prevents PowerShell from enumerating the byte[]
}

# --- .ico (256px PNG wrapped in an ICO container) ---
[byte[]]$png256 = Get-PngBytes (New-IconBitmap 256)
$icoStream = New-Object System.IO.MemoryStream
$bw = New-Object System.IO.BinaryWriter($icoStream)
$bw.Write([System.UInt16]0)              # reserved
$bw.Write([System.UInt16]1)              # type = icon
$bw.Write([System.UInt16]1)              # image count
$bw.Write([System.Byte]0)                # width  (0 => 256)
$bw.Write([System.Byte]0)                # height (0 => 256)
$bw.Write([System.Byte]0)                # palette
$bw.Write([System.Byte]0)                # reserved
$bw.Write([System.UInt16]1)              # color planes
$bw.Write([System.UInt16]32)             # bits per pixel
$bw.Write([System.UInt32]$png256.Length) # image size
$bw.Write([System.UInt32]22)             # offset (6 + 16)
$bw.Write($png256)
$bw.Flush()
[System.IO.File]::WriteAllBytes((Join-Path $AssetsDir "partnera.ico"), $icoStream.ToArray())
$bw.Dispose()

# --- web icon (512px PNG, base64) embedded as source ---
[byte[]]$png512 = Get-PngBytes (New-IconBitmap 512)
$b64 = [System.Convert]::ToBase64String($png512)
$ts = @"
/**
 * Partnera brand icon (512x512 PNG, base64) used for the PWA manifest and
 * favicon. Generated by scripts/make-icon.ps1 - do not edit by hand.
 */
export const ICON_PNG_BASE64 =
  "$b64";
"@
$brandFile = Join-Path $Root "packages\web\src\brand-icon.ts"
[System.IO.File]::WriteAllText($brandFile, $ts, (New-Object System.Text.UTF8Encoding($false)))

Write-Host "Icon generated:" -ForegroundColor Green
Write-Host "  assets\partnera.ico"
Write-Host "  packages\web\src\brand-icon.ts"
